### ISSUE TITLE
Transfer all fragment models to Signavio

### ISSUE THREAD

**Issue by tommartensen** [bptlab/bookshelf-docs#1]
- [x] All fragment models are modeled in Signavio
- [x] All object life cycles are modeled in Signavio
- [x] The exported `BPMN XML 2.0` files are added to the [docs-repo](https://github.com/bptlab/bookshelf-docs).

**Comment by julianweise** [comment]
Assumption: Task only covers process as presented in midterm-presentation (=> Not covering doing inventory)
