### ISSUE TITLE
[GoodsTag] Investigate Event Handling

### ISSUE THREAD

**Issue by Johannes-Schneider** [bptlab/bookshelf-docs#13]
Investigate how GoodsTag uses events (e.g. NFC tag scan event).

- [x] What exactly are event scripts?
- [x] How can we use them in order to redirect events to Unicorn?
- [x] What information can we access within these scripts?

Should be done before starting issue #9

**Comment by julianweise** [comment]
Status: Sent Thomas (GoodsTag) detailed questions via mail.

**Comment by julianweise** [comment]
Issue has ben solved by yesterdays call.
