### ISSUE TITLE
New Chimera Issues 

### ISSUE THREAD

**Issue by tommartensen** [bptlab/bookshelf-docs#17]
1. Goodstag (and probably other platforms) is not accepting `application/json` as body, but Chimera has [this hard coded](https://github.com/bptlab/chimera/blob/dev/src/main/java/de/hpi/bpt/chimera/execution/controlnodes/activity/WebServiceTaskInstance.java#L107#L109)
1. **WebserviceTasks** are not executed automatically if they are the first activity in the process fragment.
1. `Start event cannot be followed directly by a timer event` -> event-based gateway.
1. Cases are not terminated automatically.

**Comment by tommartensen** [comment]
Re: 
1. [Possible values for MediaTypes](https://docs.oracle.com/javaee/7/api/constant-values.html#javax.ws.rs.core.MediaType.APPLICATION_ATOM_XML), [Gryphon](https://github.com/bptlab/gryphon/compare/526c65da326ff9be6f9fbb51fafcb13bc3a009e0...94f9ec1d57be412678943362f6a1e066fe7bf1ab), [Chimera](https://github.com/bptlab/chimera/pull/91)

**Comment by friedow** [comment]
Could you please clarify, what needs to be discussed here?

**Comment by tommartensen** [comment]
These were the meeting preparations for last wednesday.
