### ISSUE TITLE
[Unicorn] Websocket Event Adapter

### ISSUE THREAD

**Issue by tommartensen** [bptlab/bookshelf-docs#3]
To connect to event streams that are provided on [Websocket connections](https://en.wikipedia.org/wiki/WebSocket), Unicorn needs a module that establishes a websocket connection to a specified address. 

## Design Decisions:
* When to establish connection? (Start-time, Run-time)
* How to monitor/mitigate connection issues? (peer closes connection, connection lost, ...)
* How to transform received information into events (and of which types)?

**Comment by julianweise** [comment]
Task is currently blocked due to missing information about GoodsTag-Platform and event structure.
See #13 for detailed information.
