### ISSUE TITLE
[Unicorn] Goodstag Event Adapter

### ISSUE THREAD

**Issue by tommartensen** [bptlab/bookshelf-docs#4]
@Hannes01071995 @julianweise 
Please feel free to add additional information :wink:

**Comment by Johannes-Schneider** [comment]
Duplicates issue #3

**Comment by tommartensen** [comment]
@Hannes01071995 then it was also duplicated in the presentation ;)

**Comment by Johannes-Schneider** [comment]
@tommartensen actually it was. I remembered the Unicorn event adapter approach incorrectly and therefore duplicated the actual work that needs to be done.
