### ISSUE TITLE
[Chimera/Gryphon] Implement/Deploy Process Fragments

### ISSUE THREAD

**Issue by tommartensen** [bptlab/bookshelf-docs#6]
All final process fragments must be modeled/configured in Gryphon and deployed into Chimera. 
If adaptions must be made, they shall be discussed and documented.

**Comment by julianweise** [comment]
**Prepare book**
- [ ] Message event needs query definition

**Order book**
- [x] Check why not structural sound

**Reminder**
- [ ] How to send mails from Chimera (send task)

**Comment by julianweise** [comment]
Currently blocked due to deployment issues of Chimera
